# Generated by Django 3.0.11 on 2020-11-19 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendedMovie', models.ManyToManyField(blank=True, related_name='suggestionMovie', to='movieApp.Movie', verbose_name='Önerilen Filmler')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchLater', models.ManyToManyField(blank=True, related_name='watchLater', to='movieApp.Movie', verbose_name='İzlenecek Filmler')),
                ('watchedMovie', models.ManyToManyField(blank=True, related_name='watchedMovie', to='movieApp.Movie', verbose_name='İzlenen Filmler')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ManyToManyField(related_name='followed', to='user.Member', verbose_name='Takip Edilenler')),
                ('follower', models.ManyToManyField(related_name='follower', to='user.Member', verbose_name='Takipçiler')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
            ],
        ),
    ]
