# Generated by Django 3.0.11 on 2020-11-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Oyuncu İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yönetmen İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tür İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Poster')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Puan')),
                ('cast', models.ManyToManyField(to='movieApp.Actor', verbose_name='Oyuncular')),
                ('director', models.ManyToManyField(to='movieApp.Director', verbose_name='Yönetmen')),
                ('genre', models.ManyToManyField(to='movieApp.Genre', verbose_name='Tür')),
            ],
        ),
    ]
