# Generated by Django 3.0.11 on 2021-01-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_auto_20210106_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Poster'),
        ),
    ]
