# Generated by Django 3.0.11 on 2021-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_auto_20210106_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Poster'),
        ),
    ]
